source "https://rubygems.org"

gem "mustache"
gem "mustache-sinatra"
gem "sinatra"
gem "shotgun"
gem "puma"
gem "arel"
gem "activerecord"
gem "pg_query"
gem "pg"
gem "sqlite3"
gem "pygments.rb"
gem "niceql"
gem "activesupport"
gem "rdiscount"
gem "parklife", git: "https://github.com/benpickles/parklife"
gem "iruby"
gem "treetop"