---
main:
  with:
  - alias: codes (code, name)
    values:
    - key: 'us'
      value: 'test1'
    - key: 'fr'
      value: 'France'
    
  from: data
  distinct_on:
  - data.code
  join:
  - from: codes
    alias: countries
    type: left_join
    on:
    - left: countries.code
      operator: "="
      right: data.code
